### ISSUE TITLE
Superflous API call, adding sth. to the cart

### ISSUE THREAD

**Issue by K-Duke** [paymill/paymill-shopware#2]
Invoking an ajax call to add articles to the cart using the request-uri "checkout/addArticle/sAdd/ARTICLENUMBER" results in the plugin calling executing onCheckoutConfirm.
This is due to the only cancel condition depending on sTargetAction which is not set in this circumstance.

Therefore adding article to the users shopping cart (action == "addArticle") is unnecessarily long. It should be checked if the actual action is "confirm" as well before issuing any API calls to Paymill.
This is on line 122 of Bootstrap.php

**Comment by enesf** [comment]
Thank you for your suggestion, we've added additional checking to the event handler. see: 5b889bdde42406a13ea284150fb6b2475537338b
